services:
  shuup:
    build:
      context: .
    ports:
      - "8000:8000"
    tty: true
    restart: unless-stopped
    networks:
      - shuup-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    restart: unless-stopped
    networks:
      - shuup-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - shuup-network

networks:
  shuup-network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data: