global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "shuup"
    static_configs:
      - targets: ["shuup:8000"]
    metrics_path: "/metrics"
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']